notifications:
  slack:
    - message: 'Custom message: New Probo build for project `$PROJECT_NAME` on branch `$BRANCH_NAME` at $BUILD_URL'
    webhook:
      - https://hooks.slack.com/services/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
steps:
  - name: Step 1 10 seconds
    plugin: Script
    script: |
      echo "Testing probo steps..."
      sleep 10s
  - name: Step 2 20 seconds
    plugin: Script
    script: |
      echo "Testing probo steps..."
      sleep 20s
  - name: Step 3 30 seconds
    plugin: Script
    script: |
      echo "Testing probo steps..."
      sleep 30s
  - name: Step 1 10 seconds
    plugin: Script
    script: |
      sleep 10s
      echo "Done!"
